---
argument_specs:
  main:
    short_description: An Ansible Role to update inventory sources on Ansible Controller.
    options:
      controller_inventory_sources:
        description: Data structure describing your inventory_sources to update
        type: list
        elements: dict
        options:
          name:
            required: true
            type: str
            description: Name of inventory_source
          inventory:
            required: true
            type: str
            description: Name or id of the inventory that contains the inventory source(s) to update.
          organization:
            default: None
            required: false
            type: str
            description: Name of the inventory source's inventory's organization.
          wait:
            default: None
            required: false
            type: bool
            description: Wait for the job to complete.
          interval:
            default: "{{ controller_configuration_inventory_source_update_async_delay }}"
            required: false
            type: int
            description: The interval to request an update from controller.
          timeout:
            default: None
            required: false
            type: int
            description: If waiting for the job to complete this will abort after this amount of seconds.

      # Async variables
      controller_configuration_inventory_source_updates_async_retries:
        default: "{{ controller_configuration_async_retries | default(30) }}"
        required: false
        description: This variable sets the number of retries to attempt for the role.
      controller_configuration_async_retries:
        default: 30
        required: false
        description: This variable sets number of retries across all roles as a default.
      controller_configuration_inventory_source_updates_async_delay:
        default: "{{ controller_configuration_async_delay | default(1) }}"
        required: false
        description: This variable sets delay between retries for the role.
      controller_configuration_async_delay:
        default: 1
        required: false
        description: This variable sets delay between retries across all roles as a default.


      # No_log variables
      controller_configuration_inventory_source_updates_secure_logging:
        default: "{{ controller_configuration_secure_logging | default(false) }}"
        required: false
        type: bool
        description: Whether or falset to include the sensitive tasks from this role in the log. Set this value to `true` if you will be providing your sensitive values from elsewhere.
      controller_configuration_secure_logging:
        default: false
        required: false
        type: bool
        description: This variable enables secure logging across all roles as a default.

      # Generic across all roles
      controller_state:
        default: present
        required: false
        description: The state all objects will take unless overridden by object default
        type: str
      controller_hostname:
        default: None
        required: false
        description: URL to the Ansible Controller Server.
        type: str
      controller_validate_certs:
        default: true
        required: false
        description: Whether or falset to validate the Ansible Controller Server's SSL certificate.
        type: str
      controller_username:
        default: None
        required: false
        description: Admin User on the Ansible Controller Server. Either username / password or oauthtoken need to be specified.
        type: str
      controller_password:
        default: None
        required: false
        description: Controller Admin User's password on the Ansible Controller Server. This should be stored in an Ansible Vault at vars/controller-secrets.yml or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
      controller_oauthtoken:
        default: None
        required: false
        description: Controller Admin User's token on the Ansible Controller Server. This should be stored in an Ansible Vault at or elsewhere and called from a parent playbook. Either username / password or oauthtoken need to be specified.
        type: str
...
